### ISSUE TITLE
Collision with Walls

### ISSUE THREAD

**Issue by tanmayp799** [DheGit/devcom-game-hackathon#1]
The function I implemented works fine as you would've noticed, but it fails near the corners. 
I will see if I can figure anything out, but please take a look into it once.

`ball_2 = new Ball({x:0, y:0}, 28, 2, 1); `   main.js/LINE_63
The blue ball moves out of the board near the corners.

UPDATE: Same happens with 8 ball.

**Comment by DheGit** [comment]
Sure, will look into it. Other than that, the bouncing seems cool, great job!

**Comment by DheGit** [comment]
@tanmayp799 A possible solution to this might be to turn all the equalities (==) into inequalities (>= or <=)
